name: generate animation

on:
  schedule:
      # every 6 hours
    - cron: "0 */0,5 * * *"

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Akeu-Andrade
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}

          
